import "../styles/globals.css";
import Footer from "../components/Footer";

export const metadata = {
  title: "Evolve",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Footer />
      </body>
      <script async src="https://link.msgsndr.com/js/form_embed.js" />
      <script
        async
        src="https://static.elfsight.com/platform/platform.js"
        data-use-service-core
        defer
      />
    </html>
  );
}
